### ISSUE TITLE
How to control branching through `Satisfier`?

### ISSUE THREAD

**Issue by thomaseizinger** [apoelstra/rust-miniscript#35]
I am currently trying to use miniscript to create HTLCs and construct the redeem/refund transaction for it.

However, I run into the limitation that I never get a chance to state somewhere, which branch of the script I'd like to execute for my spending transaction. It always places `01` onto the witness stack.

Is this by design?
The only way on how to overcome that at the moment is to manually modify the witness stack after the call to `satisfy`. However, that doesn't seem to be the most elegant solution.

**Comment by thomaseizinger** [comment]
Nevermind, I figured out that the satisfier is smart enough to try and explore which paths can be resolved. I forgot to pass `height` into the satisfier, hence my `refund` path could never be satisfied!

**Comment by apoelstra** [comment]
I'm encouraged by these "Miniscript is broken ... no wait, it's right and I'm wrong" comments.

With bare Script it's inevitable that these sorts of simple mistakes would eventually translate into a security vulnerability.
