### ISSUE TITLE
Compiling invalid policy "thresh(1,thresh)" causes "index out of bounds: the len is 0 but the index is 0"

### ISSUE THREAD

**Issue by practicalswift** [apoelstra/rust-miniscript#45]
Compiling invalid policy `thresh(1,thresh)` causes `index out of bounds: the len is 0 but the index is 0`.

Crash location:

https://github.com/apoelstra/rust-miniscript/blob/2aee5708e3e4f29a4d41301adc998d6b95fc4c76/src/policy/concrete.rs#L334-L335

**Comment by sanket1729** [comment]
Fixed by #50
