### ISSUE TITLE
Compiling invalid policy "and(pk())" causes assertion failure

### ISSUE THREAD

**Issue by practicalswift** [apoelstra/rust-miniscript#46]
Compiling invalid policy `and(pk())` causes assertion failure:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
```

Crash location:

https://github.com/apoelstra/rust-miniscript/blob/2aee5708e3e4f29a4d41301adc998d6b95fc4c76/src/policy/compiler.rs#L811-L812

**Comment by sanket1729** [comment]
Fixed by #50
