### ISSUE TITLE
Compiling invalid policy "thresh(2,pk(),thresh(0))" causes "index out of bounds: the len is 0 but the index is 0"

### ISSUE THREAD

**Issue by practicalswift** [apoelstra/rust-miniscript#47]
Compiling invalid policy `thresh(2,pk(),thresh(0))` causes `index out of bounds: the len is 0 but the index is 0`.

Crash location:

https://github.com/apoelstra/rust-miniscript/blob/2aee5708e3e4f29a4d41301adc998d6b95fc4c76/src/policy/compiler.rs#L950-L950

**Comment by sanket1729** [comment]
Fixed by #50
