### ISSUE TITLE
Compiling invalid policy "thresh(2,pk(),thresh(0,pk()))" causes "threshold subs, which we just compiled, typeck: TypeCheck("fragment «thresh(0,jtvc:pk_h())» has a threshold value of 0")"

### ISSUE THREAD

**Issue by practicalswift** [apoelstra/rust-miniscript#48]
Compiling invalid policy `thresh(2,pk(),thresh(0,pk()))` causes `threshold subs, which we just compiled, typeck: TypeCheck("fragment «thresh(0,jtvc:pk_h())» has a threshold value of 0")`.

Crash location:

https://github.com/apoelstra/rust-miniscript/blob/2aee5708e3e4f29a4d41301adc998d6b95fc4c76/src/policy/compiler.rs#L960-L964

**Comment by sanket1729** [comment]
Fixed by #50 .
