### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by Sosthene00** [apoelstra/rust-miniscript#53]
Hi, Rust noob here :)
I have Rust and Cargo installed, I can run `cargo build` in the repo and it doesn't return any error, but then when I try `cargo run`, it tells me this: `error: a bin target must be available for cargo run`
It seems I'm lacking a binary file, but I don't know where it's supposed to be, I had a look in the `target` directory but didn't found it, can someone help me on this?

**Comment by dpc** [comment]
This is a library. API is document here: https://docs.rs/miniscript/0.10.0/miniscript/ 

You'll have to write a binary yourself. Or run one of the exampbles with `cargo run --example <name>`
