### ISSUE TITLE
Bugfix: roundtrip_miniscript_script fails on `006400675168`

### ISSUE THREAD

**Issue by apoelstra** [apoelstra/rust-miniscript#67]
This is `OP_0 OP_NOTIF OP_0 OP_ELSE OP_PUSHNUM_1 OP_ENDIF` which winds up swapping the 0 and the 1.

**Comment by kiminuo** [comment]
@apoelstra My attempt to tackle it: https://github.com/apoelstra/rust-miniscript/pull/75
