### ISSUE TITLE
uncompressed pubkeys in wsh is mistakenly allowed

### ISSUE THREAD

**Issue by achow101** [apoelstra/rust-miniscript#73]
Uncompressed pubkeys are non-standard in segwit, but rust-miniscript is not errorring if an uncompressed pubkey is present in a witness thing (e.g. wsh)

**Comment by kiminuo** [comment]
@achow101 @apoelstra I have played with this a bit and I have come up with: https://github.com/kiminuo/rust-miniscript/commit/5fc8aef7c4b25d83bc855e2385ca9f4c94c54b1d

Could you have a quick look? Do you have some test case in mind?

**Comment by apoelstra** [comment]
Sorry @kiminuo, I'm just seeing this now a month later.

Yeah, I like this approach.

**Comment by apoelstra** [comment]
Should be fixed by #97
