### ISSUE TITLE
Inconsistent translate_pk method signatures

### ISSUE THREAD

**Issue by stevenroose** [apoelstra/rust-miniscript#76]
Is there a particular reason why there are different signatures for the `translate_pk` methods on the various types?

- `Descriptor::translate_pk` has
```rust
        mut translatefpk: Fpk,
        mut translatefpkh: Fpkh,
    where
        Fpk: FnMut(&Pk) -> Result<Q, E>,
        Fpkh: FnMut(&Pk::Hash) -> Result<Q::Hash, E>,
```
- `Miniscript::translate_pk` has
```rust
        translatefpk: &mut FPk,
        translatefpkh: &mut FPkh,
    where
        FPk: FnMut(&Pk) -> Result<Q, Error>,
        FPkh: FnMut(&Pk::Hash) -> Result<Q::Hash, Error>,
```
- Terminal::translate_pk` has
```rust
        translatefpk: &mut FPk,
        translatefpkh: &mut FPkh,
    where
        FPk: FnMut(&Pk) -> Result<Q, Error>,
        FPkh: FnMut(&Pk::Hash) -> Result<Q::Hash, Error>,
```
- `Policy::translate_pk` (both semantic and concrete) has 
```rust
        mut translatefpk: Fpk
    where
        Fpk: FnMut(&Pk) -> Result<Q, E>,
```

**Comment by apoelstra** [comment]
Looks like an oversight. I think I'd prefer they all be generic.

**Comment by stevenroose** [comment]
Well the difference is that some require a mutable reference to the method and other want the method itself. I don't think there's a reason why methods would have different requirements on that part.

But I also don't think I could say which is the best way to go that makes it easiest UX-wise. I'd say a mutable reference so that a user could decide to keep the method around for longer than the translate session?

**Comment by apoelstra** [comment]
Oh right. I want them all to just take the method itself (if you have a `FnMut` then a mutable reference will also satisfy the `FnMut` trait). But we can't do this because Rust's type system gets itself in a bind trying to handle recursive calls. So instead, on the "user-facing" functions we take the method, and on the "internal" functions we take mutable references.

IOW, try to fix it and you'll see why these are the way they are :)

**Comment by stevenroose** [comment]
Kay, so you're saying this is for a reason? Then you can close this :)

**Comment by apoelstra** [comment]
Yes :)
