### ISSUE TITLE
Update for latest (and hopefully final) changes to the language

### ISSUE THREAD

**Issue by apoelstra** [apoelstra/rust-miniscript#81]
See https://github.com/sipa/miniscript/pull/33

These changes make descriptor/miniscript parsing unambiguous (or at least, equivalent in terms of script whenever there is an ambiguity).

**Comment by sanket1729** [comment]
Should `s:pk(K)` be parsed as `sc:pk_k(K)`, or is it just applicable to `pk(K) -> c:pk_k(K)`

**Comment by sanket1729** [comment]
- [ ] Rename pk to pk_k
- [ ] Rename thresh_m to multi
- [ ] Add alias pk(K) = c:pk_k(K)
- [ ] Add alias pkh(K) = c:pk_h(K)
