### ISSUE TITLE
Tests in fuzz directory

### ISSUE THREAD

**Issue by sanket1729** [apoelstra/rust-miniscript#91]
I guess the purpose of duplicate_crash() functions to replicate crashes on Travis for debugging, but I don't think they should belong in the fuzz directory. 
The current codebase seems to have the same fuzz test extend_from_vec across all files.

**Comment by apoelstra** [comment]
Right - `duplicate_crash` isn't there for regression tests. (These should go in the main tree, not the `fuzz/` directory.) It's just a convenience function for copy/pasting the output of a failed fuzztest so you can check whether a fix works.

Agree that's a bit wasteful that `extend_from_vec` is duplicated across every single fuzztest. We could factor it out. Even more wastefully, it is duplicated in every fuzztest in rust-bitcoin and rust-secp and bitcoin_hashes as well :)

@sanket1729 can you PR to bring `duplicate_crash_2` out of fuzz/ to somewhere else?

**Comment by kiminuo** [comment]
@apoelstra @sanket1729 What about this #96?
