### ISSUE TITLE
fuzz_targets/roundtrip_policy.rs fails with 6f7228706b282929 (~ "or(pk())")

### ISSUE THREAD

**Issue by kiminuo** [apoelstra/rust-miniscript#92]
Steps to reproduce:

1. Put `6f7228706b282929` to `fuzz_targets/roundtrip_policy.rs :: duplicate_crash()`
1. Run test

Output:

```
thread 'tests::duplicate_crash_3' panicked at 'assertion failed: `(left == right)`
  left: `"or(pk())"`,
 right: `"or(1@pk())"`', fuzz_targets/roundtrip_policy.rs:17:9
```

**Comment by apoelstra** [comment]
Hmm, gross. I don't really want to ban either of these forms.

**Comment by sanket1729** [comment]
This behaviour is expected, so I think we should either remove the test or modify the test so that it explicitly adds `1@` whenever missing.

**Comment by apoelstra** [comment]
We definitely want to keep this fuzztest. It's found a lot of bugs.

I think adding/removing `1@` (not sure which one is necessary) is the way to do.

**Comment by sanket1729** [comment]
We do not aim for non-malleability in policies. We aim for non-malleability for Miniscript. Policies are not directly used in bitcoin transactions, but Miniscript it. 

On another note, I think `or()` and `and()` with a single argument should be banned. As such both of those should be invalid policies.
